#pragma once

#define URL ":2121/device/"
#define ACTUALTEMPERATURE "/1/ACTUAL_TEMPERATURE"
#define SETPOINTTEMPERATURE "/1/SET_POINT_TEMPERATURE"
#define HUMIDITY "/1/HUMIDITY"
#define ACTIVEPROFILE "/1/ACTIVE_PROFILE"
#define WINDOWSTATE "/1/WINDOW_STATE"
#define DRSSTATE "/STATE"
#define PV "/~pv"

#define NTP_SERVER "de.pool.ntp.org"
#define TZ_INFO "WEST-1DWEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00" // Western European Time

#define BACKLIGHT_SWITCHOFF_TIME_SEC (60 * 1000)
