#pragma once

#define URL ":2121/device/"
#define ACTUALTEMPERATURE "/1/ACTUAL_TEMPERATURE"
#define SETPOINTTEMPERATURE "/1/SET_POINT_TEMPERATURE"
#define HUMIDITY "/1/HUMIDITY"
#define ACTIVEPROFILE "/1/ACTIVE_PROFILE"
#define WINDOWSTATE "/1/WINDOW_STATE"
#define DRSSTATE "/STATE"
#define PV "/~pv"

#define BACKLIGHT_SWITCHOFF_TIME_SEC (60 * 1000)
